/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericErrorModel,
  InlineObject,
} from '../models/index';
import {
    GenericErrorModelFromJSON,
    GenericErrorModelToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/index';

/**
 * 
 */
export class TagsApi extends runtime.BaseAPI {

    /**
     * Get tags. Auth not required
     * Get tags
     */
    async getTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tags`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * Get tags. Auth not required
     * Get tags
     */
    async getTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.getTagsRaw(initOverrides);
        return await response.value();
    }

}
