/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateUser } from './UpdateUser';
import {
    UpdateUserFromJSON,
    UpdateUserFromJSONTyped,
    UpdateUserToJSON,
    UpdateUserToJSONTyped,
} from './UpdateUser';

/**
 * 
 * @export
 * @interface ActualizarUsuarioActualRequest
 */
export interface ActualizarUsuarioActualRequest {
    /**
     * 
     * @type {UpdateUser}
     * @memberof ActualizarUsuarioActualRequest
     */
    user: UpdateUser;
}

/**
 * Check if a given object implements the ActualizarUsuarioActualRequest interface.
 */
export function instanceOfActualizarUsuarioActualRequest(value: object): value is ActualizarUsuarioActualRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ActualizarUsuarioActualRequestFromJSON(json: any): ActualizarUsuarioActualRequest {
    return ActualizarUsuarioActualRequestFromJSONTyped(json, false);
}

export function ActualizarUsuarioActualRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActualizarUsuarioActualRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UpdateUserFromJSON(json['user']),
    };
}

export function ActualizarUsuarioActualRequestToJSON(json: any): ActualizarUsuarioActualRequest {
    return ActualizarUsuarioActualRequestToJSONTyped(json, false);
}

export function ActualizarUsuarioActualRequestToJSONTyped(value?: ActualizarUsuarioActualRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UpdateUserToJSON(value['user']),
    };
}

