/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewArticle } from './NewArticle';
import {
    NewArticleFromJSON,
    NewArticleFromJSONTyped,
    NewArticleToJSON,
    NewArticleToJSONTyped,
} from './NewArticle';

/**
 * 
 * @export
 * @interface CreateArticleRequest
 */
export interface CreateArticleRequest {
    /**
     * 
     * @type {NewArticle}
     * @memberof CreateArticleRequest
     */
    article: NewArticle;
}

/**
 * Check if a given object implements the CreateArticleRequest interface.
 */
export function instanceOfCreateArticleRequest(value: object): value is CreateArticleRequest {
    if (!('article' in value) || value['article'] === undefined) return false;
    return true;
}

export function CreateArticleRequestFromJSON(json: any): CreateArticleRequest {
    return CreateArticleRequestFromJSONTyped(json, false);
}

export function CreateArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'article': NewArticleFromJSON(json['article']),
    };
}

export function CreateArticleRequestToJSON(json: any): CreateArticleRequest {
    return CreateArticleRequestToJSONTyped(json, false);
}

export function CreateArticleRequestToJSONTyped(value?: CreateArticleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': NewArticleToJSON(value['article']),
    };
}

