/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewArticle } from './NewArticle';
import {
    NewArticleFromJSON,
    NewArticleFromJSONTyped,
    NewArticleToJSON,
    NewArticleToJSONTyped,
} from './NewArticle';

/**
 * 
 * @export
 * @interface CrearArticuloRequest
 */
export interface CrearArticuloRequest {
    /**
     * 
     * @type {NewArticle}
     * @memberof CrearArticuloRequest
     */
    article: NewArticle;
}

/**
 * Check if a given object implements the CrearArticuloRequest interface.
 */
export function instanceOfCrearArticuloRequest(value: object): value is CrearArticuloRequest {
    if (!('article' in value) || value['article'] === undefined) return false;
    return true;
}

export function CrearArticuloRequestFromJSON(json: any): CrearArticuloRequest {
    return CrearArticuloRequestFromJSONTyped(json, false);
}

export function CrearArticuloRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearArticuloRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'article': NewArticleFromJSON(json['article']),
    };
}

export function CrearArticuloRequestToJSON(json: any): CrearArticuloRequest {
    return CrearArticuloRequestToJSONTyped(json, false);
}

export function CrearArticuloRequestToJSONTyped(value?: CrearArticuloRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': NewArticleToJSON(value['article']),
    };
}

