/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewUser } from './NewUser';
import {
    NewUserFromJSON,
    NewUserFromJSONTyped,
    NewUserToJSON,
    NewUserToJSONTyped,
} from './NewUser';

/**
 * 
 * @export
 * @interface CrearUsuarioRequest
 */
export interface CrearUsuarioRequest {
    /**
     * 
     * @type {NewUser}
     * @memberof CrearUsuarioRequest
     */
    user: NewUser;
}

/**
 * Check if a given object implements the CrearUsuarioRequest interface.
 */
export function instanceOfCrearUsuarioRequest(value: object): value is CrearUsuarioRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function CrearUsuarioRequestFromJSON(json: any): CrearUsuarioRequest {
    return CrearUsuarioRequestFromJSONTyped(json, false);
}

export function CrearUsuarioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrearUsuarioRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': NewUserFromJSON(json['user']),
    };
}

export function CrearUsuarioRequestToJSON(json: any): CrearUsuarioRequest {
    return CrearUsuarioRequestToJSONTyped(json, false);
}

export function CrearUsuarioRequestToJSONTyped(value?: CrearUsuarioRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': NewUserToJSON(value['user']),
    };
}

