/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Documentación del API de Conduit
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewComment } from './NewComment';
import {
    NewCommentFromJSON,
    NewCommentFromJSONTyped,
    NewCommentToJSON,
    NewCommentToJSONTyped,
} from './NewComment';

/**
 * 
 * @export
 * @interface CreateArticleCommentRequest
 */
export interface CreateArticleCommentRequest {
    /**
     * 
     * @type {NewComment}
     * @memberof CreateArticleCommentRequest
     */
    comment: NewComment;
}

/**
 * Check if a given object implements the CreateArticleCommentRequest interface.
 */
export function instanceOfCreateArticleCommentRequest(value: object): value is CreateArticleCommentRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function CreateArticleCommentRequestFromJSON(json: any): CreateArticleCommentRequest {
    return CreateArticleCommentRequestFromJSONTyped(json, false);
}

export function CreateArticleCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': NewCommentFromJSON(json['comment']),
    };
}

export function CreateArticleCommentRequestToJSON(json: any): CreateArticleCommentRequest {
    return CreateArticleCommentRequestToJSONTyped(json, false);
}

export function CreateArticleCommentRequestToJSONTyped(value?: CreateArticleCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': NewCommentToJSON(value['comment']),
    };
}

