/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginUser } from './LoginUser';
import {
    LoginUserFromJSON,
    LoginUserFromJSONTyped,
    LoginUserToJSON,
    LoginUserToJSONTyped,
} from './LoginUser';

/**
 * 
 * @export
 * @interface IniciarSesionRequest
 */
export interface IniciarSesionRequest {
    /**
     * 
     * @type {LoginUser}
     * @memberof IniciarSesionRequest
     */
    user: LoginUser;
}

/**
 * Check if a given object implements the IniciarSesionRequest interface.
 */
export function instanceOfIniciarSesionRequest(value: object): value is IniciarSesionRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function IniciarSesionRequestFromJSON(json: any): IniciarSesionRequest {
    return IniciarSesionRequestFromJSONTyped(json, false);
}

export function IniciarSesionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IniciarSesionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': LoginUserFromJSON(json['user']),
    };
}

export function IniciarSesionRequestToJSON(json: any): IniciarSesionRequest {
    return IniciarSesionRequestToJSONTyped(json, false);
}

export function IniciarSesionRequestToJSONTyped(value?: IniciarSesionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': LoginUserToJSON(value['user']),
    };
}

