/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Documentación del API de Conduit
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface InlineObject6
 */
export interface InlineObject6 {
    /**
     * 
     * @type {User}
     * @memberof InlineObject6
     */
    user: User;
}

/**
 * Check if a given object implements the InlineObject6 interface.
 */
export function instanceOfInlineObject6(value: object): value is InlineObject6 {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function InlineObject6FromJSON(json: any): InlineObject6 {
    return InlineObject6FromJSONTyped(json, false);
}

export function InlineObject6FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject6 {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
    };
}

export function InlineObject6ToJSON(json: any): InlineObject6 {
    return InlineObject6ToJSONTyped(json, false);
}

export function InlineObject6ToJSONTyped(value?: InlineObject6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
    };
}

