/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface InlineObject5
 */
export interface InlineObject5 {
    /**
     * 
     * @type {Profile}
     * @memberof InlineObject5
     */
    profile: Profile;
}

/**
 * Check if a given object implements the InlineObject5 interface.
 */
export function instanceOfInlineObject5(value: object): value is InlineObject5 {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function InlineObject5FromJSON(json: any): InlineObject5 {
    return InlineObject5FromJSONTyped(json, false);
}

export function InlineObject5FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject5 {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ProfileFromJSON(json['profile']),
    };
}

export function InlineObject5ToJSON(json: any): InlineObject5 {
    return InlineObject5ToJSONTyped(json, false);
}

export function InlineObject5ToJSONTyped(value?: InlineObject5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ProfileToJSON(value['profile']),
    };
}

