/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Documentación del API de Conduit
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * 
     * @type {Comment}
     * @memberof InlineObject1
     */
    comment: Comment;
}

/**
 * Check if a given object implements the InlineObject1 interface.
 */
export function instanceOfInlineObject1(value: object): value is InlineObject1 {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function InlineObject1FromJSON(json: any): InlineObject1 {
    return InlineObject1FromJSONTyped(json, false);
}

export function InlineObject1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject1 {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': CommentFromJSON(json['comment']),
    };
}

export function InlineObject1ToJSON(json: any): InlineObject1 {
    return InlineObject1ToJSONTyped(json, false);
}

export function InlineObject1ToJSONTyped(value?: InlineObject1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': CommentToJSON(value['comment']),
    };
}

