/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Article } from './Article';
import {
    ArticleFromJSON,
    ArticleFromJSONTyped,
    ArticleToJSON,
    ArticleToJSONTyped,
} from './Article';

/**
 * 
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3 {
    /**
     * 
     * @type {Article}
     * @memberof InlineObject3
     */
    article: Article;
}

/**
 * Check if a given object implements the InlineObject3 interface.
 */
export function instanceOfInlineObject3(value: object): value is InlineObject3 {
    if (!('article' in value) || value['article'] === undefined) return false;
    return true;
}

export function InlineObject3FromJSON(json: any): InlineObject3 {
    return InlineObject3FromJSONTyped(json, false);
}

export function InlineObject3FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject3 {
    if (json == null) {
        return json;
    }
    return {
        
        'article': ArticleFromJSON(json['article']),
    };
}

export function InlineObject3ToJSON(json: any): InlineObject3 {
    return InlineObject3ToJSONTyped(json, false);
}

export function InlineObject3ToJSONTyped(value?: InlineObject3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': ArticleToJSON(value['article']),
    };
}

