/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InlineObject4ArticlesInner } from './InlineObject4ArticlesInner';
import {
    InlineObject4ArticlesInnerFromJSON,
    InlineObject4ArticlesInnerFromJSONTyped,
    InlineObject4ArticlesInnerToJSON,
    InlineObject4ArticlesInnerToJSONTyped,
} from './InlineObject4ArticlesInner';

/**
 * 
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
    /**
     * 
     * @type {Array<InlineObject4ArticlesInner>}
     * @memberof InlineObject4
     */
    articles: Array<InlineObject4ArticlesInner>;
    /**
     * 
     * @type {number}
     * @memberof InlineObject4
     */
    articlesCount: number;
}

/**
 * Check if a given object implements the InlineObject4 interface.
 */
export function instanceOfInlineObject4(value: object): value is InlineObject4 {
    if (!('articles' in value) || value['articles'] === undefined) return false;
    if (!('articlesCount' in value) || value['articlesCount'] === undefined) return false;
    return true;
}

export function InlineObject4FromJSON(json: any): InlineObject4 {
    return InlineObject4FromJSONTyped(json, false);
}

export function InlineObject4FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject4 {
    if (json == null) {
        return json;
    }
    return {
        
        'articles': ((json['articles'] as Array<any>).map(InlineObject4ArticlesInnerFromJSON)),
        'articlesCount': json['articlesCount'],
    };
}

export function InlineObject4ToJSON(json: any): InlineObject4 {
    return InlineObject4ToJSONTyped(json, false);
}

export function InlineObject4ToJSONTyped(value?: InlineObject4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'articles': ((value['articles'] as Array<any>).map(InlineObject4ArticlesInnerToJSON)),
        'articlesCount': value['articlesCount'],
    };
}

