/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Documentación del API de Conduit
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateArticle } from './UpdateArticle';
import {
    UpdateArticleFromJSON,
    UpdateArticleFromJSONTyped,
    UpdateArticleToJSON,
    UpdateArticleToJSONTyped,
} from './UpdateArticle';

/**
 * 
 * @export
 * @interface UpdateArticleRequest
 */
export interface UpdateArticleRequest {
    /**
     * 
     * @type {UpdateArticle}
     * @memberof UpdateArticleRequest
     */
    article: UpdateArticle;
}

/**
 * Check if a given object implements the UpdateArticleRequest interface.
 */
export function instanceOfUpdateArticleRequest(value: object): value is UpdateArticleRequest {
    if (!('article' in value) || value['article'] === undefined) return false;
    return true;
}

export function UpdateArticleRequestFromJSON(json: any): UpdateArticleRequest {
    return UpdateArticleRequestFromJSONTyped(json, false);
}

export function UpdateArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateArticleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'article': UpdateArticleFromJSON(json['article']),
    };
}

export function UpdateArticleRequestToJSON(json: any): UpdateArticleRequest {
    return UpdateArticleRequestToJSONTyped(json, false);
}

export function UpdateArticleRequestToJSONTyped(value?: UpdateArticleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': UpdateArticleToJSON(value['article']),
    };
}

