/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Documentación del API de Conduit
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateUser } from './UpdateUser';
import {
    UpdateUserFromJSON,
    UpdateUserFromJSONTyped,
    UpdateUserToJSON,
    UpdateUserToJSONTyped,
} from './UpdateUser';

/**
 * 
 * @export
 * @interface UpdateCurrentUserRequest
 */
export interface UpdateCurrentUserRequest {
    /**
     * 
     * @type {UpdateUser}
     * @memberof UpdateCurrentUserRequest
     */
    user: UpdateUser;
}

/**
 * Check if a given object implements the UpdateCurrentUserRequest interface.
 */
export function instanceOfUpdateCurrentUserRequest(value: object): value is UpdateCurrentUserRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UpdateCurrentUserRequestFromJSON(json: any): UpdateCurrentUserRequest {
    return UpdateCurrentUserRequestFromJSONTyped(json, false);
}

export function UpdateCurrentUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCurrentUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UpdateUserFromJSON(json['user']),
    };
}

export function UpdateCurrentUserRequestToJSON(json: any): UpdateCurrentUserRequest {
    return UpdateCurrentUserRequestToJSONTyped(json, false);
}

export function UpdateCurrentUserRequestToJSONTyped(value?: UpdateCurrentUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UpdateUserToJSON(value['user']),
    };
}

