/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericErrorModelErrors
 */
export interface GenericErrorModelErrors {
    /**
     * 
     * @type {Array<string>}
     * @memberof GenericErrorModelErrors
     */
    body: Array<string>;
}

/**
 * Check if a given object implements the GenericErrorModelErrors interface.
 */
export function instanceOfGenericErrorModelErrors(value: object): value is GenericErrorModelErrors {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function GenericErrorModelErrorsFromJSON(json: any): GenericErrorModelErrors {
    return GenericErrorModelErrorsFromJSONTyped(json, false);
}

export function GenericErrorModelErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericErrorModelErrors {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function GenericErrorModelErrorsToJSON(json: any): GenericErrorModelErrors {
    return GenericErrorModelErrorsToJSONTyped(json, false);
}

export function GenericErrorModelErrorsToJSONTyped(value?: GenericErrorModelErrors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

